import turtle
#goto RGB colour wheel for taking colorin graphics
ratna=turtle.Turtle()
ratna.speed(1)
ratna.color("cyan")
ratna.begin_fill()
ratna.color("blue")
ratna.forward(100)
ratna.left(90)
ratna.color("red")
ratna.forward(100)
ratna.left(90)
ratna.color("green")
ratna.forward(100)
ratna.left(90)
ratna.color("yellow")
ratna.forward(100)
ratna.end_fill()

ratna.penup()
ratna.forward(100)
ratna.pendown()

ratna.color("cyan")
ratna.begin_fill()
ratna.color("blue")
ratna.forward(100)
ratna.left(90)
ratna.color("red")
ratna.forward(100)
ratna.left(90)
ratna.color("green")
ratna.forward(100)
ratna.left(90)
ratna.color("yellow")
ratna.forward(100)
ratna.end_fill()

turtle.done()

